# -*- coding: utf-8 -*-
"""unemployment analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17m2q9vFADcN3BXDUWCX19BfVojR1TfrF
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

import plotly.express as px

data = pd.read_csv("Unemployment in India.csv")

data = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

print(data.head())

print(data.isnull().sum())

data.columns=["States","Data","Frequency",
               "Estimated Unemployment Rate",
               "Estimated Employed",
                "Estimated Labour Participation Rate",
                "Region","longitude",'latitude']

plt.style.use('seaborn-whitegrid')

plt.figure(figsize=(12,10))

sns.heatmap(data.corr())

plt.show()

data.columns =  ["States","Date","Frequency",
                  "Estimated Unemployment Rate",
                   "Estimated Employed",
                    "Estimated Labour Participation Rate",
                  "Region","longitude","latitude"]

plt.title("India Unemployment")

sns.histplot(x="Estimated Employed", hue="Region", data=data)

plt.show()

plt.figure(figsize=(12,10))

plt.title("India Unemployment")

sns.histplot(x="Estimated Unemployment Rate",
               hue = "Region", data=data)

plt.show()

unemployment = data[["States", "Region" , "Estimated Unemployment Rate"]]

figure = px.sunburst(unemployment, path=["Region","States" ],
                     values="Estimated Unemployment Rate",
                     width=700, height = 700 , color_continuous_scale="RdY1Gn",
                     title="Unemployment Rate in India")

figure.show()

