# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15lMt6voyOV82bBFfWnod32Q1IOTB44eI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv('Iris.csv')

df.head()

df.head(15)

df.tail()

df.shape

df.isnull().sum()

df.dtypes

data = df.groupby('Species')

data.head()

df['Species'].unique()

df.info()

"""visualizing

"""

plt.boxplot(df['SepalLengthCm'])

plt.boxplot(df['SepalWidthCm'])

plt.boxplot(df['PetalLengthCm'])

plt.boxplot(df['PetalWidthCm'])

sns.heatmap(df.corr())

"""DATA PREPARATION

"""

df.drop('Id',axis=1,inplace=True)

sp={'Iris-setosa': 1 , 'Iris-versicolor' : 2 , 'Iris-virginica' : 3}

df.Species=[sp[i] for i in df.Species]

df

x=df.iloc[:,0:4]

x

y=df.iloc[:,4]

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

"""TRAINING MODEL

"""

model=LinearRegression()

model.fit(x,y)

model.score(x,y)

model.coef_

model.intercept_

"""MAKING PREDICTION"""

y_pred = model.predict(x_test)

"""MODEL EVOLUTION

"""

print("mean squared error : %.2f" % np.mean((y_pred-y_test)**2))

